# Generated by Django 4.2.27 on 2026-01-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0009_alter_plantcareprofile_indoor_outdoor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sellable', models.BooleanField(default=False)),
                ('propagation_method', models.CharField(help_text='Seed / Cutting / Grafting / Tissue Culture', max_length=100)),
                ('grow_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('nursery_notes', models.TextField(blank=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursery', to='plants.plant')),
            ],
        ),
    ]
