# Generated by Django 4.2.27 on 2026-01-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plantcareprofile_indoor_outdoor_and_more'),
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='plants.plant')),
            ],
            options={
                'unique_together': {('plant', 'email')},
            },
        ),
    ]
