# Generated by Django 4.2.27 on 2026-01-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(db_index=True, max_length=200)),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('family', models.CharField(db_index=True, max_length=100)),
                ('genus', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('medicinal_uses', models.TextField(blank=True)),
                ('growth_conditions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
    ]
