# Generated by Django 4.2.27 on 2026-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='growth_habit',
            field=models.CharField(blank=True, help_text='e.g. upright, trailing, climbing', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='lifecycle',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('perennial', 'Perennial')], max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='origin_region',
            field=models.CharField(blank=True, help_text='Native region or origin', max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('tree', 'Tree'), ('shrub', 'Shrub'), ('herb', 'Herb'), ('succulent', 'Succulent'), ('climber', 'Climber'), ('creeper', 'Creeper'), ('aquatic', 'Aquatic'), ('fungal', 'Fungal')], max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
