# Generated by Django 4.2.27 on 2026-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_growth_habit_plant_lifecycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier', max_length=220, null=True, unique=True),
        ),
    ]
