# Generated by Django 4.2.27 on 2026-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(default=1, help_text='URL-friendly unique identifier', max_length=220, unique=True),
            preserve_default=False,
        ),
    ]
