# Generated by Django 4.2.27 on 2026-01-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_requirement', models.CharField(help_text='e.g. Full sun, Partial shade, Bright indirect', max_length=50)),
                ('watering_frequency', models.CharField(help_text='e.g. Every 2–3 days, Weekly, When topsoil dries', max_length=100)),
                ('overwatering_signs', models.TextField(blank=True)),
                ('underwatering_signs', models.TextField(blank=True)),
                ('soil_type', models.CharField(help_text='e.g. Well-draining loam with sand', max_length=100)),
                ('temperature_range', models.CharField(help_text='e.g. 18–35°C', max_length=50)),
                ('humidity_preference', models.CharField(blank=True, max_length=50)),
                ('indoor_outdoor', models.CharField(help_text='Indoor / Outdoor / Both', max_length=50)),
                ('pot_or_ground', models.CharField(help_text='Pot / Ground / Both', max_length=50)),
                ('growth_speed', models.CharField(blank=True, max_length=50)),
                ('expected_height', models.CharField(blank=True, max_length=50)),
                ('beginner_mistakes', models.TextField(blank=True)),
                ('toxicity_notes', models.TextField(blank=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateCareOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_zone', models.CharField(choices=[('tropical', 'Tropical'), ('subtropical', 'Subtropical'), ('arid', 'Arid'), ('temperate', 'Temperate')], max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('monsoon', 'Monsoon'), ('winter', 'Winter')], max_length=20)),
                ('watering_adjustment', models.TextField(help_text='e.g. Reduce watering during monsoon')),
                ('sunlight_adjustment', models.TextField(blank=True)),
                ('special_notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_care', to='plants.plant')),
            ],
            options={
                'unique_together': {('plant', 'climate_zone', 'season')},
            },
        ),
    ]
