# Generated by Django 4.2.27 on 2026-01-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plantcareprofile_climatecareoverride'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='climatecareoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='climatecareoverride',
            name='care_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='climate_overrides', to='plants.plantcareprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climatecareoverride',
            name='watering_adjustment',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='climatecareoverride',
            unique_together={('care_profile', 'climate_zone', 'season')},
        ),
        migrations.RemoveField(
            model_name='climatecareoverride',
            name='plant',
        ),
    ]
