# Generated by Django 4.2.27 on 2026-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_climatecareoverride_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='growth_conditions',
        ),
        migrations.AddField(
            model_name='plant',
            name='agricultural_uses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='bark_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='canopy_spread',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='cultural_significance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruit_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='height',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='leaf_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='native_range',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='toxicity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(help_text='General botanical overview'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_habit',
            field=models.CharField(blank=True, help_text='Upright, spreading, trailing, climbing, etc.', max_length=150),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='indoor_outdoor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='light_requirement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='pot_or_ground',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='soil_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='temperature_range',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='watering_frequency',
            field=models.CharField(max_length=100),
        ),
    ]
