# Generated by Django 4.2.27 on 2026-01-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_remove_plant_growth_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcareprofile',
            name='indoor_outdoor',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantcareprofile',
            name='pot_or_ground',
            field=models.CharField(choices=[('pot', 'Pot'), ('ground', 'Ground'), ('both', 'Both')], max_length=20),
        ),
    ]
