# Generated by Django 4.2.27 on 2026-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plantcareprofile_indoor_outdoor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier', max_length=220, null=True, unique=True),
        ),
    ]
